%2D gas disk interferometry V2
%15 06 2020 Start

%This script simulates a 2D Mach-Zehnder interferometer in which one path
%contains a disk jet of gas of index n(x). The goal is to plot the resulting
%intensity on a screen which corresponds to the output of the device.

%V1: Gas index profile is a definite function of space, analytical model
%V2: Gas index profile is an arbitrary discrete function of space

%



close all



lambda = 632.8 * 10^-9;      %HeNe wavelength in m
n = 1.00027751;             %Optical index of Argon gas @632.8nm normal conditions
r = 10 * 10^-3;                      %Radius of the gas flow in m
I0 = 1;                     %Incident intensity
alpha_deg = 0.01;
alpha_rad = alpha_deg *pi/180;
L = 10*10^-2;   %Length of gas jet analysis zone
N = 10001;      %Corresponds to 10000 intervals, each interval represents 10 microns N must be odd.

x = linspace(-L/2,L/2,N);    %Creation of the 1D study points in m

index = ones(N,N);

for i = 1:N
    for j = 1:N
        if sqrt(((i-((N+1)/2))^2) + ((j-((N+1)/2))^2))< 1000
            index(i,j) = n;   
        end 
    end
end



delta_phi_gas = (L/N)*(2*pi/lambda) .* sum(index-ones(N,N),2)';

delta_phi_tilt = (2*pi/lambda) * alpha_rad * x; %Phase shift due to tilt of angle alpha between the two wavefronts
i = lambda/alpha_rad;   %Fringe spacing of tilt fringes in m

I_screen = I0*(1+cos(delta_phi_gas+delta_phi_tilt));


% figure
% surf(index(4000:5000,4000:5000));     %Plotting the profile
% movegui('northwest')

figure
plot(x,delta_phi_tilt + delta_phi_gas);
movegui('northwest')

figure
plot(1000*x,I_screen);
xlabel('x position on screen in mm')
ylabel('Simulated output intensity on screen')
title('1D interferogram generated by a 10mm radius gas jet and 0.01° tilt')
movegui('northeast')




